export enum FileType {
  Constant = "constant",
  Dbrow = "dbrow",
  Dbtable = "dbtable",
  Enum = "enum",
  Hunt = "hunt",
  Idk = "idk",
  If = "if",
  Inv = "inv",
  Loc = "loc",
  Mesanim = "mesanim",
  Npc = "npc",
  Ob2 = "ob2",
  Obj = "obj",
  Param = "param",
  Rs2 = "rs2",
  Seq = "seq",
  Spotanim = "spotanim",
  Struct = "struct",
  Synth = "synth",
  Varbit = "varbit",
  Varn = "varn",
  Varp = "varp",
  Vars = "vars",
  Pack = "pack"
}
