export enum Language {
  Runescript = "runescript",
  Locconfig = "locconfig",
  Objconfig = "objconfig",
  Npcconfig = "npcconfig",
  Dbtableconfig = "dbtableconfig",
  Dbrowconfig = "dbrowconfig",
  Paramconfig = "paramconfig",
  Structconfig = "structconfig",
  Enumconfig = "enumconfig",
  Varpconfig = "varpconfig",
  Varbitconfig = "varbitconfig",
  Varnconfig = "varnconfig",
  Varsconfig = "varsconfig",
  Invconfig = "invconfig",
  Seqconfig = "seqconfig",
  Spotanimconfig = "spotanimconfig",
  Mesanimconfig = "mesanimconfig",
  Idkconfig = "idkconfig",
  Huntconfig = "huntconfig",
  Constants = "constants",
  Interface = "interface",
  Pack = "pack",
  Floconfig = "floconfig"
}
