export enum SemanticTokenType {
  Namespace = 'namespace',
  Class = 'class',
  Enum = 'enum',
  Interface = 'interface',
  Struct = 'struct',
  TypeParameter = 'typeParameter',
  Type = 'type',
  Parameter = 'parameter',
  Variable = 'variable',
  Property = 'property',
  EnumMember = 'enumMember',
  Event = 'event',
  Function = 'function',
  Method = 'method',
  Macro = 'macro',
  Keyword = 'keyword',
  Modifier = 'modifier',
  Comment = 'comment',
  String = 'string',
  Number = 'number',
  Regexp = 'regexp',
  Operator = 'operator'
}
